add missing include
to fix:
```cpp
In file included from /build/source/testing/include/gz/common/testing/AutoLogFixture.hh:58,
                 from /build/source/src/MaterialDensity_TEST.cc:20:
/build/source/testing/include/gz/common/testing/detail/AutoLogFixture.hh: In member function 'virtual void gz::common::testing::AutoLogFixture::SetUp()':
/build/source/testing/include/gz/common/testing/detail/AutoLogFixture.hh:79:8: error: 'replace' is not a member of 'std'
   79 |   std::replace(this->dataPtr->logFilename.begin(),
      |        ^~~~~~~
```

Signed-off-by: Guilhem Saurel <guilhem.saurel@laas.fr>