Fix compiling under linux
add stdlint.h to fix compiling failure

69/86] Building CXX object profiler/src/CMakeFiles/gz-common5-profiler.dir/RemoteryProfilerImpl.cc.o
FAILED: profiler/src/CMakeFiles/gz-common5-profiler.dir/RemoteryProfilerImpl.cc.o 
/usr/bin/c++ -DGZ_PROFILER_ENABLE=1 -DGZ_PROFILER_REMOTERY=1 -DRMT_USE_METAL=0 -Dgz_common5_profiler_EXPORTS -I/home/r/software/gazebosim/gz-common/include -I/home/r/build/gz-common5/include -I/home/r/software/gazebosim/gz-common/profiler/include -I/home/r/build/gz-common5/profiler/include -I/home/r/software/gazebosim/gz-common/profiler/src/Remotery/lib -I/home/r/build/gz-common5/profiler/src -I/home/r/build/gz-common5/core/include -isystem /usr/local/include/gz/utils2 -isystem /usr/include/uuid -O2 -g -DNDEBUG  -Wall -Wextra -Wno-long-long -Wno-unused-value -Wfloat-equal -Wshadow -Winit-self -Wswitch-default -Wmissing-include-dirs -pedantic -UNDEBUG -std=c++17 -fPIC -fvisibility=default -msse -msse2 -mfpmath=sse -msse3 -mssse3 -msse4.1 -msse4.2 -fPIC -I/usr/include/uuid -MD -MT profiler/src/CMakeFiles/gz-common5-profiler.dir/RemoteryProfilerImpl.cc.o -MF profiler/src/CMakeFiles/gz-common5-profiler.dir/RemoteryProfilerImpl.cc.o.d -o profiler/src/CMakeFiles/gz-common5-profiler.dir/RemoteryProfilerImpl.cc.o -c /home/r/software/gazebosim/gz-common/profiler/src/RemoteryProfilerImpl.cc
In file included from /home/r/software/gazebosim/gz-common/profiler/src/RemoteryProfilerImpl.hh:26,
                 from /home/r/software/gazebosim/gz-common/profiler/src/RemoteryProfilerImpl.cc:20:
/home/r/software/gazebosim/gz-common/profiler/src/ProfilerImpl.hh:56:59: error: ‘uint32_t’ has not been declared
   56 |       public: virtual void BeginSample(const char *_name, uint32_t *_hash) = 0;
      |                                                           ^~~~~~~~
/home/r/software/gazebosim/gz-common/profiler/src/RemoteryProfilerImpl.hh:74:51: error: ‘uint32_t’ has not been declared


Signed-off-by: mosfet80 <realeandrea@yahoo.it>