add missing include
to fix:
```cpp
/build/source/test/performance/logging.cc: In function 'void {anonymous}::PrintStats(const std::string&, const std::map<long unsigned int, std::vector<long unsigned int> >&, uint64_t)':
/build/source/test/performance/logging.cc:79:16: error: 'max_element' is not a member of 'std'; did you mean 'tuple_element'?
   79 |         (*std::max_element(t_result.second.begin(), t_result.second.end()));
      |                ^~~~~~~~~~~
```

Signed-off-by: Guilhem Saurel <guilhem.saurel@laas.fr>